const questions = [
  {
    scenario: `**Product Type:** Linux-based Router\n**Methodology:** Document-Driven Compliance (IT department)\n**Tooling:** Commercial SCA tooling (on-prem), supports firmware\n**OSS Artifacts:** Autogenerated from SCA tool\n\n**Process:**\n1. Build OS (production) image (2.4 GB)\n2. Upload image into the SCA tool\n3. Execute scan\n4. Produce SBOM\n5. Generate OSS notices\n6. Verify CVEs and licenses\n\n**Results:**\n- Tool executed scan without errors\n- Valid SBOM for 4 OSS packages\n- All licenses were permissive\n- Legal notices generated\n\n**Red Flags:**\n- Only 4 packages in a 2.4 GB Linux image\n- Licenses detected all permissive (suspicious)\n- Multi-format scan support unclear\n\nIs this correct?`,
    answer: "No",
    feedback: "Only 4 OSS packages in a full Linux image is unrealistic. Licensing coverage is likely incomplete."
  },
  {
    scenario: `**Product Type:** Java Web Platform (Maven)\n**Methodology:** Document-Driven Compliance (Security)\n**Tooling:** Maven SBOM plugin + Commercial SCA tool\n**OSS Artifacts:** Empty, assumed no open source\n\n**Process:**\n1. Build software and generate SBOM\n2. Import SBOM into SCA tool\n3. Generate CVE and license reports\n4. If licenses permissive, proceed. Else, ask Legal\n\n**Results:**\n- Valid SBOM for 78 Maven components\n- No problematic licenses\n\n**Red Flags:**\n- SBOM had no license info; SCA inferred them\n- Inference without artifact verification is risky\n- No validation close to source\n\nIs this correct?`,
    answer: "No",
    feedback: "Licenses were inferred, which can be incorrect. There was no verification close to the source."
  },
  {
    scenario: `**Product Type:** PHP Web Platform using PEAR\n**Methodology:** Technical Validation (SCA vendor)\n**Tooling:** Commercial SCA tooling (service)\n**OSS Artifacts:** Self-attributed\n\n**Process:**\n1. Tarball code into a folder\n2. Send to SCA vendor for scan\n3. Verify CVEs and licenses\n\n**Results:**\n- 96 PHP PEAR components detected\n- 18 WordPress-related packages\n- All marked as PHP PEAR licensed\n\n**Red Flags:**\n- GPL/AGPL licenses not detected\n- Some packages were commercial\n- PHP code can't be self-attributed\n\nIs this correct?`,
    answer: "No",
    feedback: "Important licenses were missed, including GPL/AGPL. PHP can't be self-attributed."
  },
  {
    scenario: `**Product Type:** SoC Vendor SDK\n**Methodology:** SBOM Technical (vendor)\n**Tooling:** Unknown\n**OSS Artifacts:** Provided by vendor under NDA\n\n**Process:**\n1. Download SDK copy\n2. Import SBOM into SCA tool\n3. Verify CVEs and licenses\n\n**Results:**\n- Valid SBOM for 118 components\n- No problematic licenses\n\n**Red Flags:**\n- SBOM merged from multiple tools\n- Kernel binaries missing\n- Not all SDK files were included\n\nIs this correct?`,
    answer: "No",
    feedback: "Merged SBOMs often miss important components. Kernel binaries were not accounted for."
  },
  {
    scenario: `**Product Type:** SoC Vendor SDK\n**Methodology:** Technical Validation (Compliance Engineer)\n**Tooling:** Commercial SCA tooling\n**OSS Artifacts:** Provided by vendor under NDA\n\n**Process:**\n1. Upload SDK tarball into SCA tool\n2. Execute scan\n3. Verify results\n\n**Results:**\n- Valid scan report for 87 components\n\n**Red Flags:**\n- Binary components not recognized were omitted\n\nIs this correct?`,
    answer: "No",
    feedback: "Unrecognized binaries were skipped — this results in an incomplete scan report."
  },
  {
    scenario: `**Product Type:** iOS Multimedia App\n**Methodology:** Document-Driven Compliance (IT/Legal)\n**Tooling:** Commercial SCA tooling (SaaS)\n**OSS Artifacts:** Generated by SaaS tool\n\n**Process:**\n1. Build a copy of the iOS app\n2. Upload to SCA tool\n3. Execute scan\n4. Produce report\n5. Verify CVEs and licenses\n\n**Results:**\n- Valid report for 53 components\n- LGPL-2.1 component dynamically linked\n- Tarball generated for LGPL component\n\n**Red Flags:**\n- Dynamic linking with LGPL not supported on iOS\n- LGPL not fully compatible with App Store\n- Codecs expected, but none reported\n\nIs this correct?`,
    answer: "No",
    feedback: "LGPL is problematic on iOS and codecs were missing. This app has compliance issues."
  }
];